import localFont from "next/font/local";
import NotifyProvider from "@/context/NotifyProvider";
import "./globals.scss";
import LoadingProvider from "@/packages/translation/LoadingProvider";
import ProgressTransition from "@/packages/translation/Loading/ProgressTransition";
import AccountProvider from "@/context/client/AccountProvider";
import SWRProvider from "@/context/SWRProvider";

const interItalicFont = localFont({
  src: "./fonts/Inter/Inter-Italic-VariableFont_opsz,wght.ttf",
  variable: "--font-inter-italic",
  weight: "100 900",
});
const interFont = localFont({
  src: "./fonts/Inter/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-inter",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${interItalicFont.variable} ${interFont.variable} antialiased`}
      >
        <LoadingProvider fallback={<ProgressTransition />}>
          <NotifyProvider>
            <SWRProvider>
              <AccountProvider>{children}</AccountProvider>
            </SWRProvider>
          </NotifyProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
