import localFont from "next/font/local";
import NotifyProvider from "@/context/NotifyProvider";
import "./globals.scss";
import LoadingProvider from "@/packages/translation/LoadingProvider";
import ProgressTransition from "@/packages/translation/Loading/ProgressTransition";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoadingProvider fallback={<ProgressTransition />}>
          <NotifyProvider>{children}</NotifyProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
