import { Suspense } from "react";
import localFont from "next/font/local";
import NotifyProvider from "@/context/NotifyProvider";
import "./globals.scss";
import LoadingProvider from "@/packages/translation/LoadingProvider";
import ProgressTransition from "@/packages/translation/Loading/ProgressTransition";
import AccountProvider from "@/context/client/AccountProvider";
import SWRProvider from "@/context/SWRProvider";

const interItalicFont = localFont({
  src: "./fonts/Inter/Inter-Italic-VariableFont_opsz,wght.ttf",
  variable: "--font-inter-italic",
  weight: "100 900",
});

const interFont = localFont({
  src: "./fonts/Inter/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-inter",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function LoadingFallback() {
  return (
    <div className="fixed inset-0 bg-white/80 flex items-center justify-center z-50">
      <div className="text-center">
        <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-blue-600 mx-auto"></div>
        <p className="mt-4 text-gray-600">Đang tải...</p>
      </div>
    </div>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="vi">
      <body
        className={`${interItalicFont.variable} ${interFont.variable} antialiased`}
      >
        <Suspense fallback={<LoadingFallback />}>
          <LoadingProvider fallback={<ProgressTransition />}>
            <NotifyProvider>
              <SWRProvider>
                <AccountProvider>
                  {children}
                </AccountProvider>
              </SWRProvider>
            </NotifyProvider>
          </LoadingProvider>
        </Suspense>
      </body>
    </html>
  );
}